version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_access
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nejo321!
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: